-- ================================================
-- 车间执行模块 (WIP) - 额外的表结构
-- ================================================

-- 6. 批记录步骤表
CREATE TABLE IF NOT EXISTS `ebr_step` (
    `id`                BIGINT       NOT NULL AUTO_INCREMENT COMMENT "主键ID",
    `ebr_id`            BIGINT       NOT NULL                COMMENT "批记录ID",
    `step_no`           INT          NOT NULL                COMMENT "步骤序号",
    `step_name`         VARCHAR(100) NOT NULL                COMMENT "步骤名称",
    `operation_code`    VARCHAR(50)  DEFAULT ""              COMMENT "工序编码",
    `operation_name`    VARCHAR(100) DEFAULT ""              COMMENT "工序名称",
    `status`            VARCHAR(20)  DEFAULT "PENDING"       COMMENT "状态：PENDING待开始/IN_PROGRESS进行中/PAUSED已暂停/COMPLETED已完成/SKIPPED已跳过",
    `start_time`        DATETIME     DEFAULT NULL            COMMENT "开始时间",
    `end_time`          DATETIME     DEFAULT NULL            COMMENT "结束时间",
    `operator_id`       BIGINT       DEFAULT NULL            COMMENT "操作员ID",
    `operator_name`     VARCHAR(50)  DEFAULT ""              COMMENT "操作员姓名（冗余）",
    `approval_status`   VARCHAR(20)  DEFAULT ""              COMMENT "审批状态：PENDING待审批/APPROVED已批准/REJECTED已拒绝",
    `approver_id`       BIGINT       DEFAULT NULL            COMMENT "审批人ID",
    `approver_name`     VARCHAR(50)  DEFAULT ""              COMMENT "审批人姓名（冗余）",
    `approval_time`     DATETIME     DEFAULT NULL            COMMENT "审批时间",
    `approval_comment`  VARCHAR(500) DEFAULT ""              COMMENT "审批意见",
    `data_record`       TEXT         DEFAULT NULL            COMMENT "数据记录（JSON格式）",
    `remark`            VARCHAR(500) DEFAULT ""              COMMENT "备注",
    `deleted`           TINYINT      DEFAULT 0               COMMENT "逻辑删除",
    `create_time`       DATETIME     DEFAULT CURRENT_TIMESTAMP COMMENT "创建时间",
    `update_time`       DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT "更新时间",
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ebr_step` (`ebr_id`, `step_no`, `deleted`),
    KEY `idx_ebr_id` (`ebr_id`),
    KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT="批记录步骤表";

-- 7. 设备使用记录表
CREATE TABLE IF NOT EXISTS `ebr_equipment_usage` (
    `id`                BIGINT       NOT NULL AUTO_INCREMENT COMMENT "主键ID",
    `ebr_id`            BIGINT       NOT NULL                COMMENT "批记录ID",
    `step_id`           BIGINT       DEFAULT NULL            COMMENT "步骤ID",
    `equipment_code`    VARCHAR(50)  NOT NULL                COMMENT "设备编码",
    `equipment_name`    VARCHAR(200) DEFAULT ""              COMMENT "设备名称",
    `equipment_type`    VARCHAR(50)  DEFAULT ""              COMMENT "设备类型",
    `start_time`        DATETIME     NOT NULL                COMMENT "开始使用时间",
    `end_time`          DATETIME     DEFAULT NULL            COMMENT "结束使用时间",
    `duration`          INT          DEFAULT 0               COMMENT "使用时长（分钟）",
    `operator_id`       BIGINT       DEFAULT NULL            COMMENT "操作员ID",
    `operator_name`     VARCHAR(50)  DEFAULT ""              COMMENT "操作员姓名（冗余）",
    `usage_status`      VARCHAR(20)  DEFAULT ""              COMMENT "使用状态：NORMAL正常/ABNORMAL异常",
    `maintenance_record` TEXT         DEFAULT NULL            COMMENT "维护记录",
    `deleted`           TINYINT      DEFAULT 0               COMMENT "逻辑删除",
    `create_time`       DATETIME     DEFAULT CURRENT_TIMESTAMP COMMENT "创建时间",
    PRIMARY KEY (`id`),
    KEY `idx_ebr_id` (`ebr_id`),
    KEY `idx_step_id` (`step_id`),
    KEY `idx_equipment_code` (`equipment_code`),
    KEY `idx_start_time` (`start_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT="设备使用记录表";

-- 8. 物料平衡表
CREATE TABLE IF NOT EXISTS `ebr_material_balance` (
    `id`                BIGINT       NOT NULL AUTO_INCREMENT COMMENT "主键ID",
    `ebr_id`            BIGINT       NOT NULL                COMMENT "批记录ID",
    `material_id`       BIGINT       NOT NULL                COMMENT "物料ID",
    `material_code`     VARCHAR(50)  DEFAULT ""              COMMENT "物料编码（冗余）",
    `material_name`     VARCHAR(200) DEFAULT ""              COMMENT "物料名称（冗余）",
    `spec`              VARCHAR(200) DEFAULT ""              COMMENT "规格型号",
    `unit_id`           BIGINT       DEFAULT NULL            COMMENT "单位ID",
    `unit_name`         VARCHAR(50)  DEFAULT ""              COMMENT "单位名称（冗余）",
    `plan_quantity`     DECIMAL(18,6) NOT NULL               COMMENT "计划用量",
    `theoretical_quantity`DECIMAL(18,6) NOT NULL            COMMENT "理论用量",
    `actual_input`      DECIMAL(18,6) DEFAULT 0              COMMENT "实际投入",
    `actual_output`     DECIMAL(18,6) DEFAULT 0              COMMENT "实际产出",
    `difference`        DECIMAL(18,6) DEFAULT 0              COMMENT "差异",
    `difference_rate`   DECIMAL(5,2) DEFAULT 0              COMMENT "差异率（%）",
    `balance_status`    VARCHAR(20)  DEFAULT "BALANCED"      COMMENT "平衡状态：BALANCED平衡/UNBALANCED不平衡",
    `remark`            VARCHAR(500) DEFAULT ""              COMMENT "备注",
    `deleted`           TINYINT      DEFAULT 0               COMMENT "逻辑删除",
    `create_time`       DATETIME     DEFAULT CURRENT_TIMESTAMP COMMENT "创建时间",
    `update_time`       DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT "更新时间",
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ebr_material` (`ebr_id`, `material_id`, `deleted`),
    KEY `idx_ebr_id` (`ebr_id`),
    KEY `idx_material_id` (`material_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT="物料平衡表";

-- 9. 领料单表
CREATE TABLE IF NOT EXISTS `material_issuance` (
    `id`                BIGINT       NOT NULL AUTO_INCREMENT COMMENT "主键ID",
    `issuance_no`       VARCHAR(50)  NOT NULL                COMMENT "领料单号",
    `issuance_type`     VARCHAR(50)  DEFAULT "PRODUCTION"   COMMENT "领料类型：PRODUCTION生产/REPAIR维修/OTHER其他",
    `department_id`     BIGINT       DEFAULT NULL            COMMENT "部门ID",
    `department_name`   VARCHAR(100) DEFAULT ""              COMMENT "部门名称（冗余）",
    `work_center_id`    BIGINT       DEFAULT NULL            COMMENT "工作中心ID",
    `work_center_name`  VARCHAR(100) DEFAULT ""              COMMENT "工作中心名称（冗余）",
    `requester_id`      BIGINT       DEFAULT NULL            COMMENT "申请人ID",
    `requester_name`    VARCHAR(50)  DEFAULT ""              COMMENT "申请人姓名（冗余）",
    `request_time`      DATETIME     DEFAULT CURRENT_TIMESTAMP COMMENT "申请时间",
    `status`            VARCHAR(20)  DEFAULT "PENDING"       COMMENT "状态：PENDING待审批/APPROVED已批准/REJECTED已拒绝/ISSUED已领料/COMPLETED已完成/CANCELLED已取消",
    `approval_status`   VARCHAR(20)  DEFAULT "PENDING"       COMMENT "审批状态：PENDING待审批/APPROVED已批准/REJECTED已拒绝",
    `approver_id`       BIGINT       DEFAULT NULL            COMMENT "审批人ID",
    `approver_name`     VARCHAR(50)  DEFAULT ""              COMMENT "审批人姓名（冗余）",
    `approval_time`     DATETIME     DEFAULT NULL            COMMENT "审批时间",
    `approval_comment`  VARCHAR(500) DEFAULT ""              COMMENT "审批意见",
    `issuer_id`         BIGINT       DEFAULT NULL            COMMENT "发料人ID",
    `issuer_name`       VARCHAR(50)  DEFAULT ""              COMMENT "发料人姓名（冗余）",
    `issue_time`        DATETIME     DEFAULT NULL            COMMENT "发料时间",
    `receiver_id`       BIGINT       DEFAULT NULL            COMMENT "收料人ID",
    `receiver_name`     VARCHAR(50)  DEFAULT ""              COMMENT "收料人姓名（冗余）",
    `receive_time`      DATETIME     DEFAULT NULL            COMMENT "收料时间",
    `remark`            TEXT         DEFAULT NULL            COMMENT "备注",
    `deleted`           TINYINT      DEFAULT 0               COMMENT "逻辑删除",
    `create_time`       DATETIME     DEFAULT CURRENT_TIMESTAMP COMMENT "创建时间",
    `update_time`       DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT "更新时间",
    `create_by`         VARCHAR(50)  DEFAULT ""              COMMENT "创建人",
    `update_by`         VARCHAR(50)  DEFAULT ""              COMMENT "更新人",
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_issuance_no` (`issuance_no`, `deleted`),
    KEY `idx_department_id` (`department_id`),
    KEY `idx_work_center_id` (`work_center_id`),
    KEY `idx_status` (`status`),
    KEY `idx_request_time` (`request_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT="领料单表";

-- 10. 领料单明细表
CREATE TABLE IF NOT EXISTS `material_issuance_detail` (
    `id`                BIGINT       NOT NULL AUTO_INCREMENT COMMENT "主键ID",
    `issuance_id`       BIGINT       NOT NULL                COMMENT "领料单ID",
    `line_no`           INT          DEFAULT 10              COMMENT "行号",
    `material_id`       BIGINT       NOT NULL                COMMENT "物料ID",
    `material_code`     VARCHAR(50)  DEFAULT ""              COMMENT "物料编码（冗余）",
    `material_name`     VARCHAR(200) DEFAULT ""              COMMENT "物料名称（冗余）",
    `spec`              VARCHAR(200) DEFAULT ""              COMMENT "规格型号",
    `unit_id`           BIGINT       DEFAULT NULL            COMMENT "单位ID",
    `unit_name`         VARCHAR(50)  DEFAULT ""              COMMENT "单位名称（冗余）",
    `request_quantity`  DECIMAL(18,4) NOT NULL               COMMENT "请领数量",
    `approval_quantity` DECIMAL(18,4) DEFAULT 0              COMMENT "批准数量",
    `issued_quantity`   DECIMAL(18,4) DEFAULT 0              COMMENT "实发数量",
    `returned_quantity` DECIMAL(18,4) DEFAULT 0              COMMENT "退料数量",
    `batch_no`          VARCHAR(50)  DEFAULT ""              COMMENT "批次号",
    `lot_no`            VARCHAR(50)  DEFAULT ""              COMMENT "批号",
    `warehouse_id`      BIGINT       DEFAULT NULL            COMMENT "仓库ID",
    `warehouse_name`    VARCHAR(100) DEFAULT ""              COMMENT "仓库名称（冗余）",
    `location`          VARCHAR(100) DEFAULT ""              COMMENT "库位",
    `unit_price`        DECIMAL(18,4) DEFAULT 0              COMMENT "单价",
    `total_price`       DECIMAL(18,4) DEFAULT 0              COMMENT "总价",
    `remark`            VARCHAR(500) DEFAULT ""              COMMENT "备注",
    `deleted`           TINYINT      DEFAULT 0               COMMENT "逻辑删除",
    `create_time`       DATETIME     DEFAULT CURRENT_TIMESTAMP COMMENT "创建时间",
    `update_time`       DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT "更新时间",
    PRIMARY KEY (`id`),
    KEY `idx_issuance_id` (`issuance_id`),
    KEY `idx_material_id` (`material_id`),
    KEY `idx_warehouse_id` (`warehouse_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT="领料单明细表";
